const activity1Research = [
  {
    slug: 'uml-requisitos', title: 'UML y requisitos del sistema', shortTitle: 'UML y requisitos',
    focus: 'Los requisitos expresan necesidades y condiciones; UML representa perspectivas del sistema y apoya la trazabilidad.',
    question: '¿Cómo se expresa una necesidad de modo que pueda analizarse, diseñarse y verificarse?',
    summary: 'Los requisitos describen las necesidades, funciones y cualidades de un sistema. UML ofrece una notación gráfica para modelar su estructura y comportamiento. La trazabilidad relaciona la necesidad con sus requisitos, modelos y verificaciones.',
    interpretation: 'La trazabilidad vincula la necesidad original con cada requisito, modelo y prueba relacionada. Ante un cambio, esa relación permite reconocer qué partes del diseño y qué verificaciones se ven afectadas.',
    visuals: [
      { file: '01-trazabilidad-requisitos.svg', source: '01-trazabilidad-requisitos.drawio', title: 'De una necesidad a la comprobación', alt: 'Diagrama que relaciona una necesidad de búsqueda con un requisito funcional, un caso de uso y una prueba; incluye una condición de calidad evaluada bajo carga y datos definidos.', caption: 'El requisito funcional describe la búsqueda; el de calidad expresa el tiempo de respuesta bajo condiciones de carga y datos definidas.' }
    ],
    sections: [
      { heading: 'De una necesidad a un requisito', body: 'Una necesidad expresa un problema o resultado esperado por una parte interesada; por ejemplo, localizar una obra sin recorrer los estantes. Un requisito convierte esa necesidad en una declaración concreta sobre las funciones o cualidades del sistema. La especificación conserva la fuente y las relaciones de cada requisito.', points: ['Necesidad: una persona quiere saber si la biblioteca tiene una obra disponible.', 'Requisito funcional: el catálogo permitirá buscar ejemplares por título o autor.', '“El catálogo será fácil de usar” expresa una expectativa subjetiva; su evaluación requiere un escenario, criterios observables y condiciones de prueba.'] },
      { heading: 'Requisitos funcionales y de calidad', body: 'Un requisito funcional define un servicio, una respuesta o una transformación que el sistema debe realizar. Describe comportamientos observables: buscar un título, registrar un préstamo o cancelar una reserva. Los requisitos no funcionales establecen cualidades o restricciones bajo las cuales operan esos servicios, por ejemplo seguridad, tiempo de respuesta, disponibilidad, compatibilidad o accesibilidad. Aunque sus categorías se presentan por separado, se relacionan: una función concreta puede tener condiciones de calidad propias.', points: ['RF-01: el sistema permitirá consultar ejemplares por título y autor.', 'RNF-01 · Propuesta verificable: al menos 95 % de las búsquedas en ≤2 s, con 5 000 ejemplares y 20 usuarios concurrentes.', 'El criterio combina umbral, volumen de datos, concurrencia y proporción de respuestas; sus valores son ilustrativos.'] },
      { heading: 'UML y sus modelos', body: 'El Lenguaje Unificado de Modelado (UML) ofrece notaciones para visualizar, especificar y documentar sistemas. Los casos de uso representan objetivos de actores; los diagramas de clases organizan tipos, atributos y relaciones; las máquinas de estados describen respuestas ante eventos. UML complementa la especificación escrita y no define por sí solo un proceso completo de desarrollo.', points: ['Un caso de uso puede mostrar la función Buscar libro vinculada al actor Estudiante.', 'Una prueba de búsqueda aporta evidencia para comprobar RF-01.', 'La relación entre requisito, diagrama y prueba evita que una función dibujada quede sin necesidad o sin verificación asociada.'] }
    ],
    related: ['requisitos', 'arquitectura'],
    physicalBook: {"title": "UML con Rational Rose", "authors": "Gesvin Romero Moreno", "publisher": "Grupo Editorial Megabyte", "year": "2004", "pages": "1.ª edición", "url": "https://biblioteca.upds.edu.bo/", "status": "Datos bibliográficos y páginas consultadas documentados en las fotografías del ejemplar físico."},
    references: [
      ['Object Management Group. (2017). Unified Modeling Language (UML), Version 2.5.1.', 'https://www.omg.org/spec/UML/2.5.1/PDF'],
      ['NASA. (2016). NASA Systems Engineering Handbook, Appendix C: How to Write a Good Requirement.', 'https://www.nasa.gov/reference/system-engineering-handbook-appendix/'],
      ['NASA Software Engineering Handbook. (s. f.). SWE-109: Software Requirements Specification.', 'https://swehb.nasa.gov/spaces/7150/pages/16449740/SWE-109%2B-%2BSoftware%2BRequirements%2BSpecification']
    ]
  },
  {
    slug: 'actores-casos', title: 'Actores y casos de uso', shortTitle: 'Actores y casos de uso',
    focus: 'La perspectiva externa: los roles que se relacionan con el sistema y los resultados que buscan.',
    question: '¿Quién interactúa con el sistema y qué resultado recibe de esa interacción?',
    summary: 'El modelo de casos de uso representa funciones del sistema desde la perspectiva de los roles externos que interactúan con él. Un actor es un rol, no necesariamente una persona individual; un caso de uso expresa un objetivo que produce un resultado observable. El límite del sistema separa esas funciones del entorno y aclara qué responsabilidades pertenecen a la solución estudiada.',
    interpretation: 'El diagrama resume el contexto, los objetivos y la participación de cada actor, pero no detalla todas las decisiones de una conversación. Una descripción textual complementaria conserva las condiciones previas, el flujo normal, las alternativas y el resultado. Esa combinación permite revisar si cada función tiene un usuario o sistema externo relacionado y si el alcance está delimitado con claridad.',
    visuals: [
      { file: '02-casos-de-uso.svg', source: '02-casos-de-uso.drawio', title: 'Actores y objetivos dentro del sistema', alt: 'Diagrama UML de casos de uso con los actores Estudiante y Bibliotecario alrededor del límite del sistema de biblioteca y cinco objetivos dentro.', caption: 'Las asociaciones indican participación; el rectángulo delimita las funciones que pertenecen al sistema de biblioteca.' }
    ],
    sections: [
      { heading: 'El actor representa un rol', body: 'En UML, el actor designa una entidad externa que intercambia información o inicia acciones con el sistema. Puede ser una persona, una organización, un dispositivo o un programa. “Estudiante” es un rol; “Ana” sería una persona que podría desempeñarlo. Una misma persona puede asumir roles diferentes en contextos distintos. El actor queda fuera del límite del sistema porque representa parte de su entorno, aunque reciba o envíe información.', points: ['Actor primario: inicia una interacción para alcanzar un objetivo, como buscar un libro.', 'Actor de apoyo: participa durante la ejecución, como un servicio externo de autenticación si forma parte del contexto estudiado.', 'La descripción del actor explica su relación con el sistema; no enumera personas concretas del equipo.'] },
      { heading: 'Objetivos y frontera del sistema', body: 'Un caso de uso reúne las interacciones que producen un resultado de valor para un actor. Su nombre suele expresar una acción y su objeto: Consultar disponibilidad o Registrar préstamo. El rectángulo de frontera indica qué funciones ofrece la solución; los actores permanecen fuera y los casos de uso aparecen dentro. La frontera evita confundir una tarea humana con una capacidad del software o ampliar el alcance sin motivo.', points: ['Buscar libro y Consultar disponibilidad son objetivos que puede iniciar un Estudiante.', 'Registrar préstamo y Registrar devolución son funciones asociadas al rol Bibliotecario.', 'La línea de asociación indica quién participa, pero no expresa el orden de las acciones ni todos los pasos del proceso.'] },
      { heading: 'Relaciones y descripción textual', body: 'Las relaciones include y extend tienen significados específicos. Include señala un comportamiento que se inserta como parte requerida de otro caso; extend añade un comportamiento condicionado que amplía el caso base. Una relación no se agrega solo para decorar el diagrama. Los detalles de precondiciones, pasos, excepciones y resultado se explican en una descripción textual del caso de uso.', points: ['Ejemplo de precondición: la cuenta del estudiante está identificada.', 'Flujo principal: el estudiante selecciona un ejemplar disponible y confirma la reserva.', 'Alternativa: si el ejemplar no está disponible, el sistema comunica la condición y no registra la reserva.'] }
    ],
    related: ['usuarios', 'funcion'],
    physicalBook: {"title": "UML con Rational Rose", "authors": "Gesvin Romero Moreno", "publisher": "Grupo Editorial Megabyte", "year": "2004", "pages": "1.ª edición", "url": "https://biblioteca.upds.edu.bo/", "status": "Datos bibliográficos y páginas consultadas documentados en las fotografías del ejemplar físico."},
    references: [
      ['Object Management Group. (2017). Unified Modeling Language (UML), Version 2.5.1, Clause 18: Use Cases.', 'https://www.omg.org/spec/UML/2.5.1/PDF'],
      ['IBM. (s. f.). The use-case model.', 'https://www.ibm.com/docs/en/rsas/7.5.0?topic=model-use-case'],
      ['IBM. (s. f.). Use cases in modeling diagrams.', 'https://www.ibm.com/docs/en/dma?topic=diagrams-use-cases']
    ]
  },
  {
    slug: 'objetos-estados', title: 'Objetos y diagramas de estado', shortTitle: 'Objetos y estados',
    focus: 'Una vista instantánea de objetos concretos y una vista temporal de los cambios que experimentan.',
    question: '¿Qué objetos existen en una situación y cómo cambia su estado cuando ocurren eventos?',
    summary: 'El diagrama de objetos presenta instancias concretas, sus valores y los enlaces que existen en un momento determinado. La máquina de estados representa las condiciones por las que pasa un elemento y las transiciones que producen eventos, acciones o condiciones de guarda. Una vista fija y una vista temporal se complementan al explicar una situación del sistema.',
    interpretation: 'Un estado se interpreta como una condición durante la vida de un objeto, no como un valor aislado de la base de datos. Una transición une un estado de origen con uno de destino y puede activarse por un evento; la guarda determina si se cumple una condición necesaria. Disponible → Reservado → Prestado → Disponible representa el ciclo de un ejemplar asociado a las funciones bibliotecarias documentadas.',
    visuals: [
      { file: '03-diagrama-de-objetos.svg', source: '03-diagrama-de-objetos.drawio', title: 'Una instantánea del préstamo', alt: 'Diagrama de objetos UML con instancias de Estudiante, Préstamo y Ejemplar, sus atributos de ejemplo y asociaciones.', caption: 'Los nombres subrayados representan instancias. Los valores describen una situación concreta, no la definición general de una clase.' },
      { file: '03-maquina-de-estados.svg', source: '03-maquina-de-estados.drawio', title: 'Estados de un ejemplar', alt: 'Máquina de estados UML que muestra Disponible, Reservado y Prestado, con transiciones reservar, retirar, devolver y vencer reserva.', caption: 'La transición representa un cambio causado por un evento. Las reglas de vencimiento son una hipótesis que debe validarse.' }
    ],
    sections: [
      { heading: 'El objeto muestra un caso concreto', body: 'Un objeto es una instancia de una clase con identidad propia y valores para sus propiedades en un momento dado. En UML, una notación como ejemplar01:Ejemplar separa el nombre de la instancia del tipo al que pertenece. Los atributos anotados describen esa instantánea: un código, un estado o una fecha. Las conexiones entre instancias muestran vínculos presentes en el escenario examinado.', points: ['estudiante03:Estudiante {id = U-38} es una instancia ilustrativa.', 'prestamo42:Prestamo {estado = Activo} enlaza a esa instancia con ejemplar01:Ejemplar.', 'Las instancias enlazan al usuario, el préstamo y el ejemplar dentro del modelo bibliotecario.'] },
      { heading: 'La máquina de estados explica cambios', body: 'Una máquina de estados describe el comportamiento de una entidad a través del tiempo. Cada estado corresponde a una condición que se mantiene hasta que sucede una transición. La transición puede nombrar un evento, una guarda y una acción: al producirse devolver() y validarse que el préstamo corresponde al ejemplar, este pasa de Prestado a Disponible y queda registrada la devolución.', points: ['Evento: devolver ejemplar. Estado de origen: Prestado. Estado de destino: Disponible.', 'Evento: vence la reserva. Cuando vence el plazo definido por la política bibliotecaria, la reserva se cierra y el ejemplar puede volver a estar Disponible.', 'La guarda representa una condición lógica de la transición; no equivale a un actor ni a una etapa arbitraria del proceso.'] },
      { heading: 'Dos diagramas, dos preguntas', body: 'El diagrama de objetos responde qué instancias y enlaces conforman una situación determinada. La máquina de estados responde qué condiciones puede atravesar un objeto y qué sucesos producen cada cambio. El primero permite examinar un escenario; el segundo, comprobar que las respuestas del sistema mantienen reglas coherentes a lo largo del ciclo de vida. Ninguno reemplaza los requisitos que definen el comportamiento esperado.', points: ['Instantánea: un préstamo activo enlaza a un estudiante con un ejemplar prestado.', 'Secuencia: Disponible → Reservado → Prestado → Disponible.', 'El ciclo puede ampliarse con renovaciones, multas, cancelaciones o reparación cuando forman parte de la política bibliotecaria.'] }
    ],
    related: ['sistema', 'relaciones'],
    physicalBook: {"title": "UML con Rational Rose", "authors": "Gesvin Romero Moreno", "publisher": "Grupo Editorial Megabyte", "year": "2004", "pages": "1.ª edición", "url": "https://biblioteca.upds.edu.bo/", "status": "Datos bibliográficos y páginas consultadas documentados en las fotografías del ejemplar físico."},
    references: [
      ['Object Management Group. (2017). Unified Modeling Language (UML), Version 2.5.1, Clauses 13 and 14: State Machines.', 'https://www.omg.org/spec/UML/2.5.1/PDF'],
      ['NASA Software Engineering Handbook. (s. f.). SWE-109: Software Requirements Specification, required states and modes.', 'https://swehb.nasa.gov/spaces/7150/pages/16449740/SWE-109%2B-%2BSoftware%2BRequirements%2BSpecification']
    ]
  },
  {
    slug: 'datos-clases', title: 'Datos, modelos y diagramas de clases y entidad-relación', shortTitle: 'Datos y clases',
    focus: 'La misma biblioteca descrita como dominio, estructura orientada a objetos y datos relacionados.',
    question: '¿Qué información conserva el sistema y cómo se representan sus relaciones?',
    summary: 'El modelado distingue conceptos del dominio de decisiones de implementación. El modelo conceptual presenta entidades y reglas; el modelo lógico determina atributos, identificadores y relaciones; el físico expresa tablas, tipos, índices y restricciones de un gestor. El diagrama de clases UML representa clases y asociaciones en un modelo orientado a objetos. El modelo entidad-relación organiza datos persistentes. Pueden describir el mismo dominio con propósitos y notaciones diferentes.',
    interpretation: 'En el ejemplo, Estudiante, Préstamo, Ejemplar y Título forman conceptos relacionados. Un estudiante puede registrar muchos préstamos a lo largo del tiempo. Cada préstamo corresponde a un ejemplar, y cada ejemplar pertenece a un título. La clase UML puede incluir operaciones y asociaciones; el esquema relacional traduce la identidad y las relaciones a claves y restricciones. Las multiplicidades y claves deben coincidir para que ambas vistas expresen las mismas reglas.',
    visuals: [
      { file: '04-diagrama-de-clases.svg', source: '04-diagrama-de-clases.drawio', title: 'Diagrama de clases UML', alt: 'Clases UML Estudiante, Prestamo, Ejemplar y Titulo con atributos, operaciones y multiplicidades de un sistema bibliotecario.', caption: 'La clase Préstamo conserva cada operación histórica. Las asociaciones expresan las reglas entre objetos.' },
      { file: '04-modelo-entidad-relacion.svg', source: '04-modelo-entidad-relacion.drawio', title: 'Modelo relacional derivado', alt: 'Modelo entidad-relación de biblioteca con las tablas ESTUDIANTE, PRESTAMO, EJEMPLAR y TITULO; claves primarias, claves foráneas y cardinalidades uno a muchos.', caption: 'Las claves foráneas implementan las relaciones uno a muchos. Cada préstamo conserva el vínculo con un estudiante y un ejemplar.' }
    ],
    sections: [
      { heading: 'Conceptual, lógico y físico', body: 'El modelo conceptual explica qué conceptos del dominio existen y qué reglas los relacionan, sin depender de un producto de base de datos. En el nivel lógico aparecen atributos, identificadores, cardinalidades y restricciones con más precisión. El nivel físico define tablas, tipos, índices, almacenamiento y sintaxis para un motor específico. La separación permite revisar primero el significado de los datos y luego sus decisiones técnicas.', points: ['Conceptual: un estudiante realiza préstamos; cada préstamo corresponde a un ejemplar.', 'Lógico: Préstamo incluye identificadores de estudiante y ejemplar, fechas y estado.', 'Físico: INTEGER, VARCHAR, índices y sintaxis se determinan al elegir el gestor y las reglas de operación.'] },
      { heading: 'UML de clases y entidad-relación', body: 'Una clase UML especifica un tipo de objetos, sus propiedades, operaciones y asociaciones. La multiplicidad indica cuántas instancias pueden participar en cada extremo de una relación. Un modelo entidad-relación se concentra en la estructura de los datos: entidades, atributos, identificadores y vínculos. En su implementación relacional, esos vínculos se traducen con claves primarias y foráneas. Ambos modelos pueden representar la misma biblioteca, pero responden a preguntas distintas y no son notaciones intercambiables.', points: ['En UML, Estudiante 1 — 0..* Préstamo significa que una instancia de Estudiante puede asociarse con cero o varios préstamos.', 'En el esquema relacional, PRESTAMO guarda estudiante_id como clave foránea hacia ESTUDIANTE.', 'UML también puede mostrar solicitarPrestamo(); el esquema entidad-relación no describe por sí mismo una operación del sistema.'] },
      { heading: 'Identidad e integridad referencial', body: 'Una clave primaria identifica de forma única cada fila de una tabla. Una clave foránea conserva una referencia a la fila relacionada y permite que el gestor compruebe la integridad referencial. En el ejemplo, separar Título de Ejemplar evita repetir el mismo ISBN, nombre y autor por cada copia física. Préstamo conecta a una persona con una copia y conserva las fechas que describen ese evento.', points: ['TITULO(title_id PK) se relaciona con EJEMPLAR(title_id FK).', 'ESTUDIANTE(student_id PK) se relaciona con PRESTAMO(student_id FK).', 'Un ejemplar participa en varios préstamos históricos; las reglas adicionales limitan los préstamos activos simultáneos.'] }
    ],
    related: ['arquitectura', 'elementos'],
    physicalBook: {"title": "Fundamentos de bases de datos", "authors": "Abraham Silberschatz, Henry F. Korth y S. Sudarshan", "publisher": "McGraw-Hill Interamericana", "year": "2014", "pages": "6.ª edición · ISBN 978-84-481-9033-0", "url": "https://biblioteca.upds.edu.bo/", "status": "Datos bibliográficos documentados en la portada y página legal fotografiadas."},
    references: [
      ['Object Management Group. (2017). Unified Modeling Language (UML), Version 2.5.1, Clause 11: Classes.', 'https://www.omg.org/spec/UML/2.5.1/PDF'],
      ['Oracle. (2018). SQL Developer Data Modeler Concepts and Usage, Version 18.1, Section 1.4: Approaches to Data Modeling.', 'https://docs.oracle.com/database/sql-developer-data-modeler-18.1/DMDUG/data-modeler-concepts-usage.htm'],
      ['Microsoft. (s. f.). Primary and foreign key constraints.', 'https://learn.microsoft.com/en-us/sql/relational-databases/tables/primary-and-foreign-key-constraints?view=sql-server-ver16'],
      ['Microsoft. (s. f.). Database normalization description.', 'https://learn.microsoft.com/en-us/office/troubleshoot/access/database-normalization-description']
    ]
  }
];
