const umlBooks = [
  {title:'Integrar UML en los proyectos', authors:'Nathalie Lopez, Jorge Migueis y Emmanuel Pichon', edition:'1.ª edición', year:'s. f.', url:'https://dspace.scz.ucb.edu.bo/dspace/handle/123456789/1392'},
  {title:'El proceso unificado de desarrollo de software', authors:'Ivar Jacobson, Grady Booch y James Rumbaugh', edition:'1.ª edición', year:'s. f.', url:'https://dspace.scz.ucb.edu.bo/dspace/handle/123456789/1178'}
];
const databaseBooks = [
  {title:'Fundamentos de sistemas de bases de datos', authors:'Shamkant B. Navathe', edition:'3.ª edición', year:'s. f.', url:'https://dspace.scz.ucb.edu.bo/dspace/handle/123456789/449'},
  {title:'Tecnología y diseño de bases de datos', authors:'Mario Piattini Velthuis', edition:'1.ª edición', year:'s. f.', url:'https://dspace.scz.ucb.edu.bo/dspace/handle/123456789/10114'}
];
const libraryCaseSource = 'https://repositorio.upea.bo/jspui/handle/123456789/917';
const umlPhysicalBook = {title:'Análisis y diseño orientado a objetos con UML y Rational Rose',authors:'Sergio Matsukawa',publisher:'Empresa Editora Macro',year:'2004',pages:'520 páginas',url:'https://biblioteca.upds.edu.bo/biblioteca/index.php?id=2516&lvl=categ_see',status:'Catálogo UPDS: ejemplar impreso registrado en Biblioteca Tarija.'};
const dbPhysicalBook = {title:'Bases de datos con SQL Server 2012',authors:'Maribel Sabana',publisher:'Megabyte',year:'2013',pages:'575 páginas · 1.ª edición',url:'https://biblioteca.upds.edu.bo/biblioteca/index.php?lvl=more_results&mode=keyword&tags=ok&user_query=Base+de+datos',status:'Catálogo UPDS: ejemplar impreso registrado como disponible en Biblioteca Tarija.'};
const umlEditors = [
  'https://editor.plantuml.com/uml/NP11JyCm38Nl-HNMxfLOZpsWGSMErJJHtjtK54jfKnmN1ByUDzfGnSdFodkVxPoIekWw1QUiWU1Ly0Tx3ZpW00E1qCVAYJKcAE2P-y1HoIEqbvSd5-XDGIC8Z-yA0mjvvJYxhU8y6kxGaAUqmIfOX6pOPAHlmoQIJqpmHVq1h3RxqFLSF1mhCusSL53-ejbwFH__cykz-SQ-USkzjyOKjwlM52iOZMdRMiAp-3MWjowdsdeVwd3xZUsnWhYGP9blMA8evKJd6YYAnxpRNPNEkgoDP-rTjdLMdJlHFAnJ-0K0',
  'https://editor.plantuml.com/uml/RL3DQiCm3BxxAKJkUONHKSQkfQCFe2IQPt2i8YaRO_JTQoTnbupTf4_V7pgeeTWqHcV18i4HbHK6WaaPMdWBQZGYTA6BWOrwbC1mERqykqZl1iOWmNyO346ejy39OMyiq9n8b1F6lRG1LAYdIhteDDj6AljCMI5NJ37vNAofLRweA_qyQOdRsMC3FoutpujcnPbyrWWAN2MpSLpZr-LVPhwHVE9CF2_pXdVaf5FC7uCU3IFxnR726-Oh9LhyhYn62jzGKeSS4p9ZzPzlxkOUpshRfzz-ExIM-GCk3lM31NkKsO9LVQ0qJ6Ey0m00',
  'https://editor.plantuml.com/uml/TOxB2W8n34Nt_OgiXVa15pA-zeFWIbpKDaWbRKgQplTRHd2S0NV9FPV3xOjQqHh9Q512E0P735auLopAu15g0dnXp6G5EZY41mLMT1QkmtblRfixTDqEJg5aJWsYcS-93D9CrZDiGV0PYaeJvIcCl2vViA2CwxPyKZFJls9CsXvhld0vRj7rE39L5pYjp8k-iyaX_QpeCVaQwGq0',
  'https://editor.plantuml.com/uml/hLJBRbCn4DtxAqPXWGHAb40VDAgg9gL1286gGbS88SUUt9ZwUeBjsr8GdyIA1NlwOuplCstI7JjxPdpcUERC78SeVInoAwA95k4jQRG4bZAZ2AIJriHq-li7fcPk3KLK4YxEJYV2uY929F0cMqRGngEAXfm8byQjf9SvMECmtgmGoCSbhJaSPmcuWltXcj5BTxbXL5Q6C8dHctaHyRKYzzvyHrWF2KkfwTgu31RI1hp_67u8WAbKbvcdmkaJikJXqUbazcps8dd8Q_IrTMUqTpATidNYFLtNnk5mVtTomCOPkLZRHYztzWxsQbl9QBIRdZL4E_DpyLCiZKR0V1Ll84UkX0v2LDmkGY6zePBZKwC_5zLz3EWYUeB3mxCtHqViT9JFFOuXuhT835azF_F8_SkxzwlQi0cm5NpM-l0ByxFIRpeNg9Po3RYyjtQDLsGBnNrlF0stqngnvRObHSUDrLVOBTGKQPDHys-0n4ANSKMENgR4RSOF9KQRRmEooHRchWDiekuMzfpbwQzaY-Mh-tylQo1h53FGNLst_r0yXbV5xIyPmBWh4tWKCK1IELV8bTmy52xTyXK5nhpzxNZ-yfMH82sWDZpdW1RoSi07eb5U_oEhKwFxL8vnlvMKQBLrFw9fh6WxV3-YQiGM19vJrs-AAreElL4F-dte3GU39xrEr6Fmc9aGlUnIFHWgkHYeUCpS0x1DIyTG5_r1rBL8XBhpeXRNtSWMO0oyq1JFFWhXU4V2d6AaN9nZQa_qXKfzhDQgXBaCKakc2YmsM1GkELC_2zwmYbryv2rZgqKx4EzuoMAQG1QHJ4t4yBN0NF9UDPdX7StPKtJ4OC90eDEGI8XZFgNL_Wy'
];
const activity1CaseStudies = [
 {slug:'uml-requisitos',institution:'UPEA · Biblioteca Central',title:'Requisitos y trazabilidad',sourceUrl:libraryCaseSource,sourceTitle:'Proyecto de grado: Sistema de información para la gestión y administración bibliotecaria con interfaz web (2013)',summary:'El caso documenta un sistema web para apoyar al personal bibliotecario con préstamos, reservas, reportes y estadísticas. La ficha declara UWE-UML para el análisis, PHP para la aplicación y PostgreSQL como gestor de datos.',boundary:'Las funciones parten del resumen publicado por la UPEA. Los criterios verificables son una especificación analítica; no se atribuyen a la tesis.',observations:['Necesidad: apoyar la gestión de la Biblioteca Central y permitir operaciones de préstamo y reserva a distancia.','RF-01: el personal registra un préstamo asociado al usuario y al ejemplar.','RF-02: el sistema registra una reserva asociada al usuario y al ejemplar.','RNF propuesto: cada operación identifica al usuario autorizado y conserva fecha y resultado.','Prueba propuesta: verificar que préstamo y reserva quedan vinculados y aparecen en el reporte correspondiente.'],books:umlBooks,physical:umlPhysicalBook,alt:'Trazabilidad desde las necesidades bibliotecarias hasta requisitos, caso de uso y verificación.',editor:umlEditors[0]},
 {slug:'actores-casos',institution:'UPEA · Biblioteca Central',title:'Actores y casos de uso',sourceUrl:libraryCaseSource,sourceTitle:'Proyecto de grado: Sistema de información para la gestión y administración bibliotecaria con interfaz web (2013)',summary:'El sistema web gestiona préstamos, reservas, reportes y estadísticas para el personal de biblioteca. Los actores y la frontera muestran quién interactúa con el sistema y qué funciones corresponden al software.',boundary:'El resumen de la tesis no publica sus diagramas detallados. Este caso de uso se deriva de las funciones documentadas; el rol de usuario lector se presenta como actor del análisis.',observations:['Personal bibliotecario: registra préstamos y reservas y consulta resultados para generar reportes.','Usuario lector: actor externo que solicita una operación bibliotecaria; las funciones públicas de autoservicio no se detallan en el resumen.','Generar reportes y estadísticas corresponde al sistema; interpretar los resultados corresponde al personal.','La frontera excluye la entrega física del ejemplar, salvo el registro digital que realiza el personal.','La ficha confirma acceso web a distancia; no detalla permisos ni autenticación.'],books:umlBooks,physical:umlPhysicalBook,alt:'Casos de uso UML para préstamos, reservas y reportes del sistema bibliotecario UPEA.',editor:umlEditors[1]},
 {slug:'objetos-estados',institution:'UPEA · Biblioteca Central',title:'Objetos y ciclo de vida',sourceUrl:libraryCaseSource,sourceTitle:'Proyecto de grado: Sistema de información para la gestión y administración bibliotecaria con interfaz web (2013)',summary:'El sistema documentado gestiona préstamos y reservas. Una instantánea de objetos muestra un ejemplar y sus operaciones; la máquina de estados representa los cambios de disponibilidad que acompañan esas funciones.',boundary:'La ficha confirma las funciones generales, no sus reglas internas. Los estados y transiciones son un modelo de análisis que debe contrastarse con las políticas de la Biblioteca Central.',observations:['Instantánea: ejemplar E-104 disponible; reserva R-230 activa para usuario U-038.','Al formalizar la entrega, se asocia el préstamo con el usuario y el ejemplar; el ejemplar queda prestado.','Al registrar la devolución, el préstamo se cierra y el ejemplar puede volver a disponible.','Guarda propuesta: no existe otro préstamo activo para esa copia.','La regla de prioridad para reservas debe definirse con la biblioteca.'],books:umlBooks,physical:umlPhysicalBook,alt:'Máquina de estados propuesta para un ejemplar en el sistema bibliotecario UPEA.',editor:umlEditors[2]},
 {slug:'datos-clases',institution:'UPEA · Biblioteca Central',title:'Clases y modelo de datos',sourceUrl:libraryCaseSource,sourceTitle:'Proyecto de grado: Sistema de información para la gestión y administración bibliotecaria con interfaz web (2013)',summary:'La tesis identifica PHP y PostgreSQL. Un modelo lógico relaciona usuarios, ejemplares, préstamos y reservas para representar las funciones bibliotecarias y preservar la integridad de los datos.',boundary:'La fuente confirma PostgreSQL, pero no especifica las tablas originales en el resumen. El diagrama es una reconstrucción lógica, no el esquema desarrollado por la autora.',observations:['Usuario 1 — 0..* Préstamo: se conserva quién recibe el ejemplar y en qué fechas.','Ejemplar 1 — 0..* Préstamo: la copia mantiene el historial; una regla limita operaciones activas simultáneas.','Usuario 1 — 0..* Reserva; Ejemplar 1 — 0..* Reserva: cada operación enlaza al lector con la copia solicitada.','Las claves primarias identifican registros y las foráneas enlazan las operaciones con sus datos relacionados.','PostgreSQL permite definir restricciones de integridad; los tipos e índices dependen de consultas y volúmenes esperados.'],books:databaseBooks,physical:dbPhysicalBook,alt:'Modelo UML de clases y datos reconstruido para las operaciones documentadas de la biblioteca UPEA.',editor:umlEditors[3]}
];
