const umlBooks = [
  {title:'Integrar UML en los proyectos',authors:'Nathalie Lopez, Jorge Migueis y Emmanuel Pichon',edition:'1.ª edición',year:'s. f.',url:'https://dspace.scz.ucb.edu.bo/dspace/handle/123456789/1392'},
  {title:'El proceso unificado de desarrollo de software',authors:'Ivar Jacobson, Grady Booch y James Rumbaugh',edition:'1.ª edición',year:'s. f.',url:'https://dspace.scz.ucb.edu.bo/dspace/handle/123456789/1178'}
];
const databaseBooks = [
  {title:'Fundamentos de sistemas de bases de datos',authors:'Shamkant B. Navathe',edition:'3.ª edición',year:'s. f.',url:'https://dspace.scz.ucb.edu.bo/dspace/handle/123456789/449'},
  {title:'Tecnología y diseño de bases de datos',authors:'Mario Piattini Velthuis',edition:'1.ª edición',year:'s. f.',url:'https://dspace.scz.ucb.edu.bo/dspace/handle/123456789/10114'}
];
const libraryCaseSource = 'https://biblioteca.upds.edu.bo/';
const umlPhysicalBook = {title:'UML con Rational Rose',authors:'Gesvin Romero Moreno',publisher:'Grupo Editorial Megabyte',year:'2004',pages:'1.ª edición',url:'https://biblioteca.upds.edu.bo/',status:'Datos bibliográficos y páginas consultadas documentados en las fotografías del ejemplar físico.'};
const dbPhysicalBook = {title:'Fundamentos de bases de datos',authors:'Abraham Silberschatz, Henry F. Korth y S. Sudarshan',publisher:'McGraw-Hill Interamericana',year:'2014',pages:'6.ª edición · ISBN 978-84-481-9033-0',url:'https://biblioteca.upds.edu.bo/',status:'Datos bibliográficos documentados en la portada y página legal fotografiadas.'};
const umlEditors = [
  'https://editor.plantuml.com/uml/NP31JeGm48RlVOh9tac41p0RCPuCCRZSk0nbbXrJMj8E9kpR-0mUJ3pAYraGDwkNpj_a-__-qtqGz3BsHWcB8IX8K-0MMvX0F9wnORDUlpuWHvdVZEiS3FDdOrWxg9xkdvMXeu0uyDoT15hsf8MTLSj4syNKtIMsjezEe-4pUXWjWciyxW035DTu-P3SfBMz6uEEdAUEWtWNLh1C_vDPRNDdmsZYAa0lr0y6FMrqTatd61oq16Dmb_GfvhzoYEh8-lHJflfZyYpaUJMYfa5Gy_nkbqVPQcuf7j4pnSt3u2p__bWCvSPiFGwgW2IvNTfl8bDbkgfAbTacgdKUr9viE_Rc6m',
  'https://editor.plantuml.com/uml/ROz1JiD034NtSmehArZq2gWY28aTQaLMtJWJDp6QZgEnfn9278PJ8B6a5sEIK6N3xdlcVV_lhHecowVWZ2qGrAYYq15a5VZvAhDTFeFq0kFbkmti1LwU7_OkqD7011BtWq77YRonH8VU947LiB9XDAe05HetVMFiIq3rpyOIrtAHOkInWdUNjGWjy7rMZmaIzQoMHETro-CArH8rXt877DaFE3EFargH7PrP2q2lT1e39j93V2krTPJ8BGVki9jzjOoCkXgV8dkU6oYbCnxYZJAGbXDWmCbesE7jRDqjYFjm3MmsTzUQox3qMVHVnZ9SNLkANJw5Nm',
  'https://editor.plantuml.com/uml/ROynQaCn38Ptdq9p8HV8K089cKDBfv91jaMYe6SzPFlT9sV84EZOTx7QQK9BwQXV7xy-hN91AtKGLxW8mLRgIM7YpBvDaI1eobKAmkSLrbZci-X1OPm_l71GUDjjNjtxqnuMYsTueHiQDSCIVCq1pVtAEhBbSCIsHMziO7JWN4pTTzo13UTH4tiMZXWRQTHiq81ED8o2HjdzOUwdoQRUh6FW-P8WtY6X__Y7nwGoaG7AZykZgcFzioLmui1DWLCXmt3hTojAiGxo1G',
  'https://editor.plantuml.com/uml/PL9BRXin3Dtp58INBMAaYsoyIj5ssGyQz00SYRRPQCI9H1aeYXuc1-Yw-_fYfSPZDq4s4Z-FudlGkwr6nTgOmCGIuqUDd1I3vi2JDKf8cTBnjqbG_Fi7tv4T7vFk50SPakYk71-tlVVjo_ixIBmrDCKYkxrXbCB1H3FKUyaJ5HenIMRxCJ5giRq-QMHVN7d2c-idnKBvVYxUG4XKAtuU2k5FU2snHvrpImeS9VGrKeSClnRessPQJjWvXApZKFZI_n35g-8APymbVO7xpkEKQ7dgd47GA3k5A7NIB8CaYHIX3H9evd8U_-ggoc4XlIImvR2dEqrEsre4za-8wYEplDMh5LvTpTT9mmQfpTpWF-VLcnFeUhrst3otmQdvbmHQddc6kAZOe0bdXalXEUvCrtTM3T9fPJN6GSrqXCKUtHCoMo9oaOEZFC2a5IEPdmUfxWwko1avOI2ZsJCdWhg6J-uHdeeloqOTmlMXyKYO1HCXbOScvkPfBaIoSSdKDtIJhO5pn4uARZrgO_e7'
];
const activity1CaseStudies = [
  {slug:'uml-requisitos',institution:'Catálogo público · UPDS',title:'Necesidades, requisitos y trazabilidad',sourceUrl:libraryCaseSource,sourceTitle:'Catálogo público de la Biblioteca UPDS',summary:'La consulta pública permite buscar registros bibliográficos, abrir una ficha, revisar ejemplares y su disponibilidad, y acceder a la opción de reserva cuando está habilitada en el registro. Estas funciones observables ofrecen un caso real para relacionar necesidades, requisitos, modelos y criterios de verificación.',boundary:'El análisis parte de funciones visibles en el catálogo público. Los requisitos y criterios de aceptación son propuestas académicas; no describen la especificación interna de UPDS.',observations:['Necesidad: localizar una obra y conocer si existe un ejemplar consultable.','RF-01 · Propuesta: buscar registros por título, autor o tema y mostrar coincidencias.','RF-02 · Propuesta: abrir la ficha y consultar ubicación y disponibilidad de cada ejemplar.','RF-03 · Propuesta: ofrecer la opción de reserva cuando el registro la presenta.','Trazabilidad: vincular cada necesidad con su requisito, caso de uso y prueba de aceptación.'],books:umlBooks,physical:umlPhysicalBook,alt:'Modelo analítico que conecta la necesidad de localizar una obra con requisitos de búsqueda, consulta de disponibilidad y verificación.',editor:umlEditors[0],photos:[['tema-01-romero-portada.jpeg','Portada del libro UML con Rational Rose, de Gesvin Romero Moreno.'],['tema-01-romero-diagramas-uml.jpeg','Página del libro que presenta los tipos de diagramas UML y su propósito.']]},
  {slug:'actores-casos',institution:'Catálogo público · UPDS',title:'Actores y casos de uso del catálogo',sourceUrl:libraryCaseSource,sourceTitle:'Catálogo público de la Biblioteca UPDS',summary:'Una persona visitante consulta el catálogo, abre registros bibliográficos y revisa datos de ejemplares. En los registros que lo permiten aparece una opción de reserva. El modelo de casos de uso separa esos objetivos del trabajo interno de la biblioteca, que el sitio público no permite observar.',boundary:'El diagrama representa interacciones disponibles desde la interfaz pública. No infiere roles, permisos ni procesos administrativos internos.',observations:['Actor: persona visitante del catálogo; el modelo describe un rol, no una identidad.','Buscar en el catálogo conduce a una lista de registros coincidentes.','Consultar ficha permite revisar los datos bibliográficos y los ejemplares asociados.','La opción de reserva se representa solo como interacción disponible en determinados registros.','Los rectángulos de caso de uso expresan objetivos; la frontera delimita el alcance visible del catálogo.'],books:umlBooks,physical:umlPhysicalBook,alt:'Diagrama UML de casos de uso propuesto a partir de la consulta pública del catálogo UPDS.',editor:umlEditors[1],photos:[['tema-02-romero-pagina-legal.jpeg','Página legal que identifica el título, autor, editorial y edición del libro.'],['tema-02-romero-casos-uso.jpeg','Páginas del libro con explicación y ejemplo de un diagrama de casos de uso.']]},
  {slug:'objetos-estados',institution:'Catálogo público · UPDS',title:'Registros, ejemplares y estados visibles',sourceUrl:libraryCaseSource,sourceTitle:'Catálogo público de la Biblioteca UPDS',summary:'La ficha bibliográfica reúne datos de una obra y presenta ejemplares con ubicación y disponibilidad. Un diagrama de objetos puede mostrar una ficha concreta; una máquina de estados analítica representa el cambio de una consulta desde el registro encontrado hasta la revisión de disponibilidad o el inicio de una reserva.',boundary:'El modelo usa datos y acciones visibles en el catálogo. Los estados del proceso interno de reserva no son públicos y no se atribuyen al sistema institucional.',observations:['Objeto ficha: una instancia concreta de obra con título, autor y datos editoriales.','Objeto ejemplar: una copia física vinculada a la ficha y con ubicación y disponibilidad consultables.','Estado observado: el catálogo presenta la disponibilidad del ejemplar al momento de la consulta.','Flujo analítico: resultado encontrado → ficha consultada → disponibilidad revisada → reserva iniciada, si la opción está disponible.','El modelo describe la interacción visible; no afirma reglas de préstamo, vencimiento o cierre de reservas.'],books:umlBooks,physical:umlPhysicalBook,alt:'Modelo de objetos y flujo de consulta analítico basado en la ficha pública y la disponibilidad de ejemplares.',editor:umlEditors[2],photos:[['tema-03-romero-secuencia-colaboracion.jpeg','Páginas del libro con diagramas de secuencia y colaboración.'],['tema-03-romero-estados.jpeg','Páginas del libro dedicadas a máquinas y diagramas de estado.']]},
  {slug:'datos-clases',institution:'Catálogo público · UPDS',title:'Clases y datos del catálogo',sourceUrl:libraryCaseSource,sourceTitle:'Catálogo público de la Biblioteca UPDS',summary:'La ficha pública permite reconocer conceptos del dominio: obra, autor, editorial y ejemplar; el registro también presenta ubicación y disponibilidad. Un modelo entidad-relación organiza esos datos y sus vínculos para explicar cómo podría estructurarse un catálogo bibliográfico.',boundary:'El diagrama es una reconstrucción conceptual basada en información visible. No representa el esquema de base de datos ni la arquitectura interna de UPDS.',observations:['Obra: datos descriptivos como título, edición e ISBN cuando están publicados.','Autor y editorial: entidades asociadas con la descripción bibliográfica.','Ejemplar: copia vinculada a una obra, con ubicación y disponibilidad consultables.','Reserva: concepto relacionado con la interacción pública cuando la ficha habilita esa opción.','Claves y cardinalidades son decisiones del modelo propuesto, no datos internos confirmados.'],books:databaseBooks,physical:dbPhysicalBook,alt:'Modelo entidad-relación conceptual para describir obras, autores, editoriales, ejemplares y reservas de un catálogo bibliográfico.',editor:umlEditors[3],photos:[['tema-04-silberschatz-portada.jpeg','Portada de Fundamentos de bases de datos, sexta edición, de Silberschatz, Korth y Sudarshan.'],['tema-04-silberschatz-er-universidad.jpeg','Ejemplo de diagrama entidad-relación para una universidad, incluido en el libro.']]}
];
