const concepts = [
 {id:'001',day:'2026-10-02',category:'Fundamentos',title:'Sistema',definition:'Conjunto de elementos relacionados que interactúan y se organizan para cumplir uno o varios objetivos. Puede recibir entradas, transformarlas y producir resultados; también se relaciona con un entorno y puede ajustar su funcionamiento mediante retroalimentación.',example:'Un sistema de inscripción recibe datos del estudiante y de las materias, valida requisitos y genera una inscripción confirmada.',activity:'SIS1-2026-10-02-001'},
 {id:'001',day:'2026-10-02',category:'Fundamentos',title:'Importancia del enfoque de sistemas',definition:'Permite comprender cómo se conectan las partes de una organización o actividad y cómo esas relaciones influyen en los resultados. Ayuda a coordinar recursos, detectar fallas y apoyar decisiones con información organizada.',activity:'SIS1-2026-10-02-001'},
 {id:'001',day:'2026-10-02',category:'Fundamentos',title:'Elementos de un sistema',definition:'Objetivo, entradas, proceso, salidas, componentes e interrelaciones, retroalimentación, control, límite, entorno y subsistemas. La terminología puede variar según el enfoque del curso.',example:'En una inscripción: los datos son entradas, la validación es el proceso y el comprobante es la salida.',activity:'SIS1-2026-10-02-001'},
 {id:'002',day:'2026-10-02',category:'Niveles',title:'Macrosistema',definition:'En un análisis jerárquico, es el nivel amplio que reúne, coordina o condiciona sistemas y subsistemas menores. Su alcance depende del límite y del nivel de análisis escogido.',example:'La universidad puede ser el macrosistema cuando se estudian sus facultades y procesos de inscripción.',activity:'SIS1-2026-10-02-002'},
 {id:'003',day:'2026-10-02',category:'Niveles',title:'Subsistema',definition:'Parte de un sistema mayor que cumple una función específica. Tiene componentes y relaciones propias, pero se coordina con otras partes para contribuir al objetivo general. También puede analizarse como un sistema.',example:'El proceso de inscripción puede ser un subsistema de la gestión académica universitaria.',activity:'SIS1-2026-10-02-003'},
 {id:'004',day:'2026-10-02',category:'Niveles',title:'Microsistema',definition:'En el modelo ecológico de Bronfenbrenner, es un entorno inmediato en el que la persona participa e interactúa directamente.',example:'La familia o el aula.',activity:'SIS1-2026-10-02-004'},
 {id:'004',day:'2026-10-02',category:'Niveles',title:'Mesosistema',definition:'Conjunto de relaciones entre los microsistemas en los que participa una persona.',example:'La comunicación entre la familia y la escuela.',activity:'SIS1-2026-10-02-004'},
 {id:'004',day:'2026-10-02',category:'Niveles',title:'Exosistema',definition:'Entorno en el que la persona no participa directamente, pero que puede afectarla a través de sus microsistemas.',example:'El horario laboral de un familiar puede cambiar la rutina en casa.',activity:'SIS1-2026-10-02-004'},
 {id:'004',day:'2026-10-02',category:'Niveles',title:'Macrosistema · modelo ecológico',definition:'Valores, normas, leyes y condiciones culturales, políticas y económicas que influyen en los demás niveles del modelo ecológico.',activity:'SIS1-2026-10-02-004'},
 {id:'005',day:'2026-10-02',category:'Clasificación',title:'Clasificación según la naturaleza',definition:'Los sistemas pueden ser naturales, formados sin diseño humano, o artificiales, creados para un fin. También pueden describirse como físicos o abstractos.',example:'El ciclo del agua es natural; un sistema de información es artificial.',activity:'SIS1-2026-10-02-005'},
 {id:'005',day:'2026-10-02',category:'Clasificación',title:'Clasificación según la complejidad',definition:'Un sistema simple tiene pocos componentes y relaciones. Uno complejo presenta más elementos e interdependencias.',activity:'SIS1-2026-10-02-005'},
 {id:'005',day:'2026-10-02',category:'Clasificación',title:'Clasificación según la automatización',definition:'Puede ser manual, semiautomatizado o automatizado, según cuánto del trabajo realizan las personas o la tecnología.',activity:'SIS1-2026-10-02-005'},
 {id:'005',day:'2026-10-02',category:'Clasificación',title:'Clasificación según la finalidad',definition:'Un sistema de propósito general sirve para diversas tareas; uno de propósito específico se diseña para una función definida.',example:'Un sistema de inscripción tiene una finalidad específica.',activity:'SIS1-2026-10-02-005'},
 {id:'006',day:'2026-10-02',category:'Sistemas de información',title:'Sistemas por función',definition:'TPS procesa transacciones; MIS produce información gerencial; DSS apoya decisiones; ESS/EIS resume información para decisiones ejecutivas; OAS apoya tareas de oficina y KMS la gestión del conocimiento.',example:'El registro de ventas puede apoyarse en un TPS; un informe periódico de ventas, en un MIS.',activity:'SIS1-2026-10-02-006'},
 {id:'006',day:'2026-10-02',category:'Sistemas de información',title:'Sistemas por arquitectura',definition:'Una arquitectura centralizada concentra procesamiento y datos; cliente-servidor distribuye solicitudes y servicios entre clientes y servidores; una arquitectura distribuida reparte componentes y tareas entre varios equipos.',activity:'SIS1-2026-10-02-006'},
 {id:'007',day:'2026-10-02',category:'Sistemas de información',title:'Sistemas por alcance',definition:'Pueden apoyar a una persona, un grupo o departamento, una organización completa o varias organizaciones conectadas.',example:'Un portal que conecta una empresa con sus proveedores tiene alcance interorganizacional.',activity:'SIS1-2026-10-02-007'},
 {id:'007',day:'2026-10-02',category:'Sistemas de información',title:'Sistemas por relación con usuarios',definition:'Un sistema puede ser interno, para integrantes de la organización; externo, para personas ajenas a ella; o mixto, para ambos grupos.',activity:'SIS1-2026-10-02-007'},
 {id:'008',day:'2026-10-02',category:'Propiedades',title:'Sinergia',definition:'La interacción entre componentes produce un resultado que supera lo que cada parte lograría por separado.',activity:'SIS1-2026-10-02-008'},
 {id:'008',day:'2026-10-02',category:'Propiedades',title:'Entropía',definition:'En el enfoque de sistemas, describe la tendencia a perder organización si el sistema no se renueva ni regula. Su uso en organizaciones es una analogía; en termodinámica tiene un significado físico preciso.',activity:'SIS1-2026-10-02-008'},
 {id:'008',day:'2026-10-02',category:'Propiedades',title:'Neguentropía',definition:'Recursos, energía o información que un sistema abierto incorpora para sostener o recuperar su organización.',activity:'SIS1-2026-10-02-008'},
 {id:'008',day:'2026-10-02',category:'Propiedades',title:'Homeostasis',definition:'Autorregulación que ayuda a mantener el funcionamiento dentro de un rango estable mientras cambian las condiciones externas. Es un equilibrio dinámico.',activity:'SIS1-2026-10-02-008'}
];

